routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('index');
Route::get('about', 'Website\AboutController@index')->name('about-us');
Route::get('contact', 'Website\ContactController@index')->name('contact-us');
Route::get('categoryshow', 'Website\CategoryController@show')->name('categoryshow');
Route::get('category/{id}','Website\CategoryController@index')->name('website_category');
Route::get('subCategory/{id}','Website\SubCategoryController@index')->name('website_subcategory');
Route::get('products/{id}','Website\ProductsController@index')->name('website_products');
Route::get('product/{id}','Website\ProductsController@show')->name('website_product');
Route::Post('guest-login','Website\HomeController@gust')->name('guest_login');

Route::get('/search','Website\ProductsController@search');
Route::group(['middleware'=>['auth']], function () {
    Route::get('checkout/{cart_id}','Website\CartController@checkoutForm')->name('website_cart_checkout');
    Route::post('checkout/{cart_id}','Website\CartController@checkout')->name('website_cart_checkout');
    Route::post('cart/{product_id}','Website\CartController@store')->name('website_cart_store');
    Route::delete('cart/{product_id}','Website\CartController@destroy')->name('website_cart_destroy');
    Route::get('cart','Website\CartController@index')->name('website_cart_view');
    Route::post('change-quantity/{id}','Website\CartController@changeQuantity');
});



Route::group(['prefix'=>'admin','middleware'=>['auth','is_admin']],function (){
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('sub-categories','Admin\SubCategoryController');
    Route::resource('has-types','Admin\HasTypeController');
    Route::resource('brands','Admin\BrandController');
    Route::resource('products','Admin\ProductsController');
    Route::resource('products/{id}/attributes','Admin\ProductsAttributesController');
    Route::resource('orders','Admin\OrdersController');
    Route::resource('admin','Admin\AdminController');
    Route::resource('users','Admin\UsersController');
    Route::resource('delivered','Admin\DeliveredController');
    Route::resource('cancel','Admin\CancelController');
    Route::patch('orders-delivered/{id}','Admin\OrdersController@delivered')->name('delivered');
    Route::patch('orders-cancel/{id}','Admin\OrdersController@cancel')->name('cancel');
});

app/Http/Controllers/Admin/OrdersController.php
<?php
/**
 * Created by PhpStorm.
 * User: laith
 * Date: 26/04/20
 * Time: 12:24 ص
 */

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Models\Cart;

class OrdersController extends Controller
{

    public function index()
    {
        // history  $orders=Cart::where('is_paid',1)->where('is_delivered','!=',0)
        //            ->paginate();

        $orders=Cart::where('is_paid',1)->where('is_delivered',0)
            ->paginate();
        return view('Admin.order.index')->with(['data'=>$orders]);
    }

    public function show($id)
    {
        $order=Cart::find($id);

        return view('Admin.order.show')->with(['item'=>$order]);
    }

    public function delivered($id)
    {
        $order=Cart::where('id',$id)->update([
            'is_delivered'=>1
        ]);

        return redirect()->back();
    }

    public function cancel($id)
    {
        $order=Cart::where('id',$id)->update([
            'is_delivered'=>2
        ]);

        return redirect()->back();
    }
}

resources/views/Admin/order/index.blade.php
@extends('layout.app')
@section('content')

    <div id='mainContent'>
        <div class="container-fluid">
            <h4 class="c-grey-900 mT-10 mB-30">{{trans('HasType.sub-categories')}}</h4>
            <div class="row">
                <div class="col-md-12">
                    <div class="bgc-white bd bdrs-3 p-20 mB-20">
                        <h4 class="c-grey-900 mB-20">{{trans('Orders.list')}}

                        </h4>

                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{{trans('order.name')}}</th>
                                <th scope="col">{{trans('order.phone_number')}}</th>
                                <th scope="col">{{trans('order.email')}}</th>
                                <th scope="col">{{trans('order.total_price')}}</th>
                                <th scope="col">{{trans('order.country')}}</th>
                                <th scope="col">{{trans('order.city')}}</th>
                                <th scope="col">action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($data as $item)
                                <tr>
                                    <th scope="row">{{$item->id}}</th>
                                    <td>{{$item->first_name}} {{$item->last_name}}</td>
                                    <td>{{$item->phone_number}}</td>
                                    <td>{{$item->email}}</td>
                                    <td>{{$item->total_price}}</td>
                                    <td>{{$item->country}}</td>
                                    <td>{{$item->city}}</td>
                                    <td>
                                        <a href="{{route('orders.show',$item->id)}}" class="btn btn-primary btn-block btn-sm">{{trans('order.details')}}</a>
                                        <br>
                                        <form method="post" action="{{route('delivered',$item->id)}}">
                                            <input type="hidden" value="patch" name="_method">
                                            @csrf
                                            <button type="submit" class="btn btn-success btn-block btn-sm">{{trans('order.delivered')}}</button>
                                        </form>
                                        <br>
                                        <form method="post" action="{{route('cancel',$item->id)}}">
                                            <input type="hidden" value="patch" name="_method">
                                            @csrf
                                            <button type="submit" class="btn btn-danger btn-block btn-sm">{{trans('order.cancel')}}</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr><td class="text-center" colspan="8">Empty</td></tr>
                            @endforelse
                            </tbody>
                        </table>
                                                {{$data->appends(Request::all())->render() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/order/show.blade.php
<?php
/**
 * @var \App\Entities\Users\User[] $data
 */
?>
@extends('layout.app')
@section('content')
    <h4 class="c-grey-900 mT-10 mB-30">{{trans('order.info')}}</h4>
    <div class="row">
        <div class="col-md-12">
            <div class="masonry-item col-12">
                <div class="bd bgc-white">
                    <div class="peers fxw-nw@lg+ ai-s">
                        <div class="peer peer-greed w-60p@lg+ w-100@lg- p-20">
                            <div class="layers">
                                <div class="layer w-100">
                                    <table class="table table-bordered">
                                        @foreach($item->CartProduct as $product)
                                        <tr>
                                            <td>{{trans('order.name')}}</td>
                                            <td>{{$product->product->title_en}}</td>
                                        </tr>

                                            <tr>
                                                <td>{{trans('order.quantity')}}</td>
                                                <td>{{$product->quantity}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('order.price')}}</td>
                                                <td>{{$product->product->price}}</td>
                                            </tr>
                                            <hr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="peer bdL p-20 w-40p@lg+ w-100p@lg-">
                            <div class="layers">
                                <div class="layer w-100">
                                    <div class="layers">
                                        <div class="layer w-100">
                                            <h5 class="mB-5"></h5>
                                        </div>
                                    </div>
                                    <div class=" pT-20 mT-20 bdT fxw-nw@lg+ jc-sb">
                                        <table class="table table-bordered">
                                            <tr>
                                                <td>{{trans('Buyer')}}</td>
                                                <td>{{$item->first_name}} {{$item->last_name}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('Buyer number')}}</td>
                                                <td>{{$item->phone_number}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('Buyer email')}}</td>
                                                <td>{{$item->email}}</td>
                                            </tr>
                                             <tr>
                                                <td>{{trans('Buyer country')}}</td>
                                                <td>{{$item->country}}</td>
                                            </tr>
                                             <tr>
                                                <td>{{trans('Buyer city')}}</td>
                                                <td>{{$item->city}}</td>
                                            </tr>

                                            <tr>
                                                <td>{{trans('Buyer street')}}</td>
                                                <td>{{$item->street}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('Buyer block')}}</td>
                                                <td>{{$item->block}}</td>
                                            </tr>

                                            <tr>
                                                <td>{{trans('Buyer apartment_number')}}</td>
                                                <td>{{$item->apartment_number}}</td>
                                            </tr>

                                            <tr>
                                                <td>{{trans('order totalPrice')}}</td>
                                                <td>{{$item->totalPrice}}</td>
                                            </tr>

                                        </table>
                                    </div>
                                </div>
                            </div>
{{--                            <a href="{{route('has-types.index')}}" class="btn btn-secondary">{{trans('has-type.back')}}</a>--}}
{{--                            <a href="{{route('has-types.edit',$item->id)}}" class="btn btn-info pull-right">{{trans('has-type.edit')}}</a>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection