routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('index');
Route::get('about', 'Website\AboutController@index')->name('about-us');
Route::get('contact', 'Website\ContactController@index')->name('contact-us');
Route::get('categoryshow', 'Website\CategoryController@show')->name('categoryshow');
Route::get('category/{id}','Website\CategoryController@index')->name('website_category');
Route::get('subCategory/{id}','Website\SubCategoryController@index')->name('website_subcategory');
Route::get('products/{id}','Website\ProductsController@index')->name('website_products');
Route::get('product/{id}','Website\ProductsController@show')->name('website_product');
Route::Post('guest-login','Website\HomeController@gust')->name('guest_login');

Route::get('/search','Website\ProductsController@search');
Route::group(['middleware'=>['auth']], function () {
    Route::get('checkout/{cart_id}','Website\CartController@checkoutForm')->name('website_cart_checkout');
    Route::post('checkout/{cart_id}','Website\CartController@checkout')->name('website_cart_checkout');
    Route::post('cart/{product_id}','Website\CartController@store')->name('website_cart_store');
    Route::delete('cart/{product_id}','Website\CartController@destroy')->name('website_cart_destroy');
    Route::get('cart','Website\CartController@index')->name('website_cart_view');
    Route::post('change-quantity/{id}','Website\CartController@changeQuantity');
});



Route::group(['prefix'=>'admin','middleware'=>['auth','is_admin']],function (){
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('sub-categories','Admin\SubCategoryController');
    Route::resource('has-types','Admin\HasTypeController');
    Route::resource('brands','Admin\BrandController');
    Route::resource('products','Admin\ProductsController');
    Route::resource('products/{id}/attributes','Admin\ProductsAttributesController');
    Route::resource('orders','Admin\OrdersController');
    Route::resource('admin','Admin\AdminController');
    Route::resource('users','Admin\UsersController');
    Route::resource('delivered','Admin\DeliveredController');
    Route::resource('cancel','Admin\CancelController');
    Route::patch('orders-delivered/{id}','Admin\OrdersController@delivered')->name('delivered');
    Route::patch('orders-cancel/{id}','Admin\OrdersController@cancel')->name('cancel');
});

resources/views/Admin/admins/index.blade.php
@extends('layout.app')
@section('content')

    <div id='mainContent'>
        <div class="container-fluid">
            <h4 class="c-grey-900 mT-10 mB-30">{{trans('admins.admins')}}</h4>
            <div class="row">
                <div class="col-md-12">
                    <div class="bgc-white bd bdrs-3 p-20 mB-20">
                        <h4 class="c-grey-900 mB-20">{{trans('admins.list')}}
                            <a href="{{route('admin.create')}}"
                               class="btn btn-success btn-sm pull-right">{{trans('admins.create')}}</a>
                        </h4>
                        {{--<form>--}}
                        {{--<div class="form-row">--}}
                        {{--<div class="form-group col-md-4 ">--}}
                        {{--<input type="text" class="form-control" id="search" name="search"--}}
                        {{--value="{{Request::get('search','')}}" placeholder="Search...">--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-4 ">--}}
                        {{--<select name="order" id="order" class="form-control">--}}
                        {{--                                        <option value="order" {{Request::get('order','created_at')=='order'?'selected':''}}>Sorted by order</option>--}}
                        {{--<option value="created_at" {{Request::get('order','created_at')=='created_at'?'selected':''}}>Sorted by date</option>--}}
                        {{--</select>--}}
                        {{--</div>--}}
                        {{--<div class="form-group">--}}
                        {{--<fieldset class="form-group">--}}
                        {{--<div class="row">--}}
                        {{--<div class="col-sm-12 form-check-inline">--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="direction"--}}
                        {{--id="direction-ascending" value="asc" {{Request::get('direction','desc')=='asc'?'checked':''}}>--}}
                        {{--{{trans('advertisements.ascending')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="direction"--}}
                        {{--id="direction-descending" value="desc" {{Request::get('direction','desc')=='desc'?'checked':''}}>--}}
                        {{--{{trans('advertisements.descending')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</fieldset>--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-10">--}}
                        {{--<fieldset class="form-group">--}}
                        {{--<div class=" form-check-inline">--}}
                        {{--<label class="col-form-legend form-check-label">{{trans('users.status')}}: </label>--}}
                        {{--<div class="col-sm-10 form-check-inline">--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="status"--}}
                        {{--id="direction-ascending" value="0" {{Request::get('status','')=='0'?'checked':''}}>--}}
                        {{--{{trans('users.suspend')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="status"--}}
                        {{--id="direction-descending" value="1" {{Request::get('status','')=='1'?'checked':''}}>--}}
                        {{--{{trans('users.active')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="status"--}}
                        {{--id="direction-descending" value="" {{Request::get('status','')==''?'checked':''}}>--}}
                        {{--{{trans('users.both')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</fieldset>--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-2">--}}
                        {{--<button type="submit" class="btn btn-info">Filter</button>--}}
                        {{--<a href="{{route('production.index')}}"  class="btn btn-outline-secondary">reset</a>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</form>--}}

                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{{trans('admins.id')}}</th>
                                <th scope="col">{{trans('admins.name')}}</th>
                                <th scope="col">{{trans('admins.email')}}</th>
                                <th scope="col">{{trans('admins.password')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($data as $item)
                                <tr>
                                    <th scope="row">{{$item->id}}</th>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->email}}</td>
                                    <td>{{$item->password}}</td>
                                    <td>
{{--                                        <a href="{{route('categories.show',$item->id)}}" class="btn btn-info btn-block btn-sm">{{trans('categories.show')}}</a>--}}
{{--                                        <br>--}}
{{--                                        <a href="{{route('categories.edit',$item->id)}}" class="btn btn-secondary btn-block btn-sm">{{trans('categories.edit')}}</a>--}}
{{--                                        <br>--}}
                                        <form method="post" action="{{route('admin.destroy',$item->id)}}">
                                            <input type="hidden" value="delete" name="_method">
                                            @csrf
                                            <button type="submit" class="btn btn-danger btn-block btn-sm">{{trans('admin.delete')}}</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr><td class="text-center" colspan="8">Empty</td></tr>
                            @endforelse
                            </tbody>
                        </table>
                                                {{$data->appends(Request::all())->render() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection