routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('index');
Route::get('about', 'Website\AboutController@index')->name('about-us');
Route::get('contact', 'Website\ContactController@index')->name('contact-us');
Route::get('categoryshow', 'Website\CategoryController@show')->name('categoryshow');
Route::get('category/{id}','Website\CategoryController@index')->name('website_category');
Route::get('subCategory/{id}','Website\SubCategoryController@index')->name('website_subcategory');
Route::get('products/{id}','Website\ProductsController@index')->name('website_products');
Route::get('product/{id}','Website\ProductsController@show')->name('website_product');
Route::Post('guest-login','Website\HomeController@gust')->name('guest_login');

Route::get('/search','Website\ProductsController@search');
Route::group(['middleware'=>['auth']], function () {
    Route::get('checkout/{cart_id}','Website\CartController@checkoutForm')->name('website_cart_checkout');
    Route::post('checkout/{cart_id}','Website\CartController@checkout')->name('website_cart_checkout');
    Route::post('cart/{product_id}','Website\CartController@store')->name('website_cart_store');
    Route::delete('cart/{product_id}','Website\CartController@destroy')->name('website_cart_destroy');
    Route::get('cart','Website\CartController@index')->name('website_cart_view');
    Route::post('change-quantity/{id}','Website\CartController@changeQuantity');
});



Route::group(['prefix'=>'admin','middleware'=>['auth','is_admin']],function (){
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('sub-categories','Admin\SubCategoryController');
    Route::resource('has-types','Admin\HasTypeController');
    Route::resource('brands','Admin\BrandController');
    Route::resource('products','Admin\ProductsController');
    Route::resource('products/{id}/attributes','Admin\ProductsAttributesController');
    Route::resource('orders','Admin\OrdersController');
    Route::resource('admin','Admin\AdminController');
    Route::resource('users','Admin\UsersController');
    Route::resource('delivered','Admin\DeliveredController');
    Route::resource('cancel','Admin\CancelController');
    Route::patch('orders-delivered/{id}','Admin\OrdersController@delivered')->name('delivered');
    Route::patch('orders-cancel/{id}','Admin\OrdersController@cancel')->name('cancel');
});

app/Models/Brand.php
<?php


namespace App\Models;


use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Brand extends Model
{

    use SoftDeletes;

    protected $fillable=[
        'title_en',
        'title_ar',
        'description_en',
        'description_ar',
        'image',
        'created_by',
    ];


    public function admin()
    {
        return $this->hasOne(User::class,'id','created_by');
    }

}

app/Http/Controllers/Admin/BrandController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Models\Brand;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class BrandController extends Controller
{
    public function index()
    {
        $brands = Brand::query()->paginate();
        return view('Admin.brands.index')->with(['data' => $brands]);
    }

    public function create()
    {
        return view('Admin.brands.forms.create');
    }

    public function store(Request $request)
    {

        $request->validate([
            'title_en' => 'required',
            'title_ar' => 'required',
            'description_en' => 'required',
            'description_ar' => 'required',
            'file' => 'required'
        ]);

        $request->offsetSet('created_by', Auth::id());
        $image = $request->file('file');
        $extension = $image->getClientOriginalExtension();
        Storage::disk('public')->put($image->getFilename() . '.' . $extension, File::get($image));
        $request->offsetSet('image', $image->getFilename() . '.' . $extension);

        Brand::create($request->all());

        return redirect()->route('brands.index');
    }

    public function show($id)
    {
        $item = Brand::find($id);
        return view('Admin.brands.show')->with(['item' => $item]);
    }

    public function edit($id)
    {
        $item = Brand::find($id);
        return view('Admin.brands.forms.edit')->with(['item' => $item]);
    }

    public function update($id, Request $request)
    {
        $request->validate([
            'title_en' => 'required',
            'title_ar' => 'required',
            'description_en' => 'required',
            'description_ar' => 'required',
        ]);
        $attributes = [
            'title_en' => $request->title_en,
            'title_ar' => $request->title_ar,
            'description_en' => $request->description_en,
            'description_ar' => $request->description_ar,
        ];

        if (isset($request->file)) {
            $image = $request->file('file');
            $extension = $image->getClientOriginalExtension();
            Storage::disk('public')->put($image->getFilename() . '.' . $extension, File::get($image));
            $request->offsetSet('image', $image->getFilename() . '.' . $extension);
            $attributes['image'] = $image->getFilename() . '.' . $extension;
        }

        Brand::query()->where('id', $id)->update($attributes);

        return redirect()->route('brands.index');
    }

    public function destroy($id)
    {
        Categories::query()->where('id', $id)->delete();
        return redirect()->route('brands.index');
    }
}

resources/views/Admin/brands/index.blade.php
@extends('layout.app')
@section('content')

    <div id='mainContent'>
        <div class="container-fluid">
            <h4 class="c-grey-900 mT-10 mB-30">{{trans('brands.brands')}}</h4>
            <div class="row">
                <div class="col-md-12">
                    <div class="bgc-white bd bdrs-3 p-20 mB-20">
                        <h4 class="c-grey-900 mB-20">{{trans('brands.list')}}
                            <a href="{{route('brands.create')}}"
                               class="btn btn-success btn-sm pull-right">{{trans('brands.create')}}</a>
                        </h4>
                        {{--<form>--}}
                        {{--<div class="form-row">--}}
                        {{--<div class="form-group col-md-4 ">--}}
                        {{--<input type="text" class="form-control" id="search" name="search"--}}
                        {{--value="{{Request::get('search','')}}" placeholder="Search...">--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-4 ">--}}
                        {{--<select name="order" id="order" class="form-control">--}}
                        {{--                                        <option value="order" {{Request::get('order','created_at')=='order'?'selected':''}}>Sorted by order</option>--}}
                        {{--<option value="created_at" {{Request::get('order','created_at')=='created_at'?'selected':''}}>Sorted by date</option>--}}
                        {{--</select>--}}
                        {{--</div>--}}
                        {{--<div class="form-group">--}}
                        {{--<fieldset class="form-group">--}}
                        {{--<div class="row">--}}
                        {{--<div class="col-sm-12 form-check-inline">--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="direction"--}}
                        {{--id="direction-ascending" value="asc" {{Request::get('direction','desc')=='asc'?'checked':''}}>--}}
                        {{--{{trans('advertisements.ascending')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="direction"--}}
                        {{--id="direction-descending" value="desc" {{Request::get('direction','desc')=='desc'?'checked':''}}>--}}
                        {{--{{trans('advertisements.descending')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</fieldset>--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-10">--}}
                        {{--<fieldset class="form-group">--}}
                        {{--<div class=" form-check-inline">--}}
                        {{--<label class="col-form-legend form-check-label">{{trans('users.status')}}: </label>--}}
                        {{--<div class="col-sm-10 form-check-inline">--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="status"--}}
                        {{--id="direction-ascending" value="0" {{Request::get('status','')=='0'?'checked':''}}>--}}
                        {{--{{trans('users.suspend')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="status"--}}
                        {{--id="direction-descending" value="1" {{Request::get('status','')=='1'?'checked':''}}>--}}
                        {{--{{trans('users.active')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--<div class="form-check">--}}
                        {{--<label class="form-check-label form-check-inline">--}}
                        {{--<input class="form-check-input" type="radio" name="status"--}}
                        {{--id="direction-descending" value="" {{Request::get('status','')==''?'checked':''}}>--}}
                        {{--{{trans('users.both')}}--}}
                        {{--</label>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</fieldset>--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-2">--}}
                        {{--<button type="submit" class="btn btn-info">Filter</button>--}}
                        {{--<a href="{{route('production.index')}}"  class="btn btn-outline-secondary">reset</a>--}}
                        {{--</div>--}}
                        {{--</div>--}}
                        {{--</form>--}}

                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{{trans('brands.title_en')}}</th>
                                <th scope="col">{{trans('brands.title_ar')}}</th>
                                <th scope="col">{{trans('brands.description_en')}}</th>
                                <th scope="col">{{trans('brands.description_en')}}</th>
                                <th scope="col">{{trans('brands.image')}}</th>
                                <th scope="col">{{trans('brands.action')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($data as $item)
                                <tr>
                                    <th scope="row">{{$item->id}}</th>
                                    <td>{{$item->title_en}}</td>
                                    <td>{{$item->title_ar}}</td>
                                    <td>{{$item->description_en}}</td>
                                    <td>{{$item->description_ar}}</td>
                                    <td><img class="imge" src="{{asset("storage/{$item->image}")}}"></td>
                                    <td>
                                        <a href="{{route('brands.show',$item->id)}}" class="btn btn-info btn-block btn-sm">{{trans('brands.show')}}</a>
                                        <br>
                                        <a href="{{route('brands.edit',$item->id)}}" class="btn btn-secondary btn-block btn-sm">{{trans('brands.edit')}}</a>
                                        <br>
                                        <form method="post" action="{{route('brands.destroy',$item->id)}}">
                                            <input type="hidden" value="delete" name="_method">
                                            @csrf
                                            <button type="submit" class="btn btn-danger btn-block btn-sm">{{trans('brands.delete')}}</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr><td class="text-center" colspan="8">Empty</td></tr>
                            @endforelse
                            </tbody>
                        </table>
                                                {{$data->appends(Request::all())->render() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/brands/show.blade.php
<?php
/**
 * @var \App\Entities\Users\User[] $data
 */
?>
@extends('layout.app')
@section('content')
    <h4 class="c-grey-900 mT-10 mB-30">{{trans('brands.info')}}</h4>
    <div class="row">
        <div class="col-md-12">
            <div class="masonry-item col-12">
                <div class="bd bgc-white">
                    <div class="peers fxw-nw@lg+ ai-s">
                        <div class="peer peer-greed w-60p@lg+ w-100@lg- p-20">
                            <div class="layers">
                                <div class="layer w-100">
                                    <div class="img-fluid">
                                        <img style="width: 80%;"
                                             src="{{asset("storage/{$item->image}")}}"
                                             alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="peer bdL p-20 w-40p@lg+ w-100p@lg-">
                            <div class="layers">
                                <div class="layer w-100">
                                    <div class="layers">
                                        <div class="layer w-100">
                                            <h5 class="mB-5"></h5>
                                        </div>
                                    </div>
                                    <div class=" pT-20 mT-20 bdT fxw-nw@lg+ jc-sb">
                                        <table class="table table-bordered">
                                            <tr>
                                                <td>{{trans('brands.title_en')}}</td>
                                                <td>{{$item->title_en}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('brands.title_ar')}}</td>
                                                <td>{{$item->title_ar}}</td>
                                            </tr>
                                             <tr>
                                                <td>{{trans('brands.description_en')}}</td>
                                                <td>{{$item->description_en}}</td>
                                            </tr>
                                             <tr>
                                                <td>{{trans('brands.description_ar')}}</td>
                                                <td>{{$item->description_ar}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('brands.created_by')}}</td>
                                                <td>{{$item->admin->name}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('brands.created_at')}}</td>
                                                <td>{{$item->created_at}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{trans('brands.update_at')}}</td>
                                                <td>{{$item->updated_at}}</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <a href="{{route('brands.index')}}" class="btn btn-secondary">{{trans('brands.back')}}</a>
                            <a href="{{route('brands.edit',$item->id)}}" class="btn btn-info pull-right">{{trans('brands.edit')}}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection